### ISSUE TITLE
uncaught Exception: PLease install pg package manually

### ISSUE THREAD

**Issue by remyd1** [libnewton/hedgenext-server#5]
Hi, I am very interested in this project, however, I have an issue at the very beginning of the install. Hedgedoc install using docker-compose is working, but not hedgenext. I deleted every containers and volumes relative to hedgedoc, to start like a fresh install for hedgenext.

**Description**

Using the `docker-compose.yml` file, I get the following error:

```
hedgenext-app-1       | 2023-08-07T13:21:40.110Z error:         uncaughtException: Please install pg package manually
hedgenext-app-1       | Error: Please install pg package manually
hedgenext-app-1       |     at ConnectionManager._loadDialectModule (/hedgedoc/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88:15)
hedgenext-app-1       |     at new ConnectionManager (/hedgedoc/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:18:24)
hedgenext-app-1       |     at new PostgresDialect (/hedgedoc/node_modules/sequelize/lib/dialects/postgres/index.js:14:30)
hedgenext-app-1       |     at new Sequelize (/hedgedoc/node_modules/sequelize/lib/sequelize.js:334:20)
hedgenext-app-1       |     at Object.<anonymous> (/hedgedoc/lib/models/index.js:25:15)
hedgenext-app-1       |     at Module._compile (node:internal/modules/cjs/loader:1191:14)
hedgenext-app-1       |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
hedgenext-app-1       |     at Module.load (node:internal/modules/cjs/loader:1069:32)
hedgenext-app-1       |     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
hedgenext-app-1       |     at Module.require (node:internal/modules/cjs/loader:1093:19)
hedgenext-app-1       |     at require (node:internal/modules/cjs/helpers:108:18)
hedgenext-app-1       |     at Object.<anonymous> (/hedgedoc/app.js:26:16)
hedgenext-app-1       |     at Module._compile (node:internal/modules/cjs/loader:1191:14)
hedgenext-app-1       |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
hedgenext-app-1       |     at Module.load (node:internal/modules/cjs/loader:1069:32)
hedgenext-app-1       |     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
hedgenext-app-1       |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
hedgenext-app-1       |     at node:internal/main/run_main_module:22:47
hedgenext-app-1 exited with code 0
```

**To Reproduce**

Copy the `.env` file and fill it with your values (I let the gotenberg.dev for PDF, otherwise, everything is complete), then copy the `docker-compose.yml` file and start it with `docker compose up`.

**Expected behavior**

A working `docker-compose.`

**Logs**

Already given before.

**Your Setup (please complete the following information):**
 - Host OS: Debian 12 Bookworm

`docker version`:

```
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:35 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:35 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

`docker volume ls`:

```
DRIVER    VOLUME NAME
local     hedgenext_database
local     opt_database
local     opt_uploads
```

**Additional context**

I found [this issue](https://stackoverflow.com/questions/55340843/error-please-install-pg-package-manually-when-trying-to-run-npm-run-servede) that might be related...

**Comment by libnewton** [comment]
Thanks for the detailed report, let me know if my latest release fixed your issue

**Comment by remyd1** [comment]
Hi,

Yes, thank you. Indeed, it works using this new dockerfile; can you publish a new container on dockerhub ?

Thanks,
Best regards,

**Comment by libnewton** [comment]
Glad it works now.
I already published a new version of the image to GHCR. It is replacing Dockerhub:
https://github.com/libnewton/hedgenext-server/pkgs/container/hedgenext-server

**Comment by remyd1** [comment]
Oh, Ok ! Can you update the `docker-compose.yml` file ?

**Comment by libnewton** [comment]
Oh good catch, will do
